services:

  users-db:
    image: postgres:17

    container_name: users-db

    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - users-data:/var/lib/postgresql/data
      - ./database/users-init.sql:/docker-entrypoint-initdb.d/users-init.sql


volumes:

  users-data: